<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="10" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-29T21:20:54 IST" name="Suite" finished-at="2021-11-29T21:20:59 IST" duration-ms="5562">
    <groups>
    </groups>
    <test started-at="2021-11-29T21:20:54 IST" name="Test" finished-at="2021-11-29T21:20:59 IST" duration-ms="5562">
      <class name="testcases.TC03_VerifyAddCustomerPage">
        <test-method signature="addNewCustomer()[pri:0, instance:testcases.TC03_VerifyAddCustomerPage@1ba9117e]" started-at="2021-11-29T21:20:58 IST" name="addNewCustomer" finished-at="2021-11-29T21:20:59 IST" duration-ms="1295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCustomer -->
      </class> <!-- testcases.TC03_VerifyAddCustomerPage -->
      <class name="testcases.TC02_Verify_ManagerHomepage">
        <test-method signature="verify_manager_home_page_title()[pri:1, instance:testcases.TC02_Verify_ManagerHomepage@a3d8174]" started-at="2021-11-29T21:20:57 IST" name="verify_manager_home_page_title" finished-at="2021-11-29T21:20:57 IST" duration-ms="68" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_manager_home_page_title -->
        <test-method signature="verifynewCustomer()[pri:2, instance:testcases.TC02_Verify_ManagerHomepage@a3d8174]" started-at="2021-11-29T21:20:57 IST" name="verifynewCustomer" finished-at="2021-11-29T21:20:58 IST" duration-ms="636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifynewCustomer -->
      </class> <!-- testcases.TC02_Verify_ManagerHomepage -->
      <class name="testcases.TC01_Verify_login_Functionality">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:testcases.TC01_Verify_login_Functionality@44821a96]" started-at="2021-11-29T21:20:49 IST" name="launchBrowser" finished-at="2021-11-29T21:20:54 IST" duration-ms="4557" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="verify_TitleAndHeader()[pri:1, instance:testcases.TC01_Verify_login_Functionality@44821a96]" started-at="2021-11-29T21:20:54 IST" name="verify_TitleAndHeader" finished-at="2021-11-29T21:20:54 IST" duration-ms="38" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title does not matched expected [uru99 Bank Home Page] but found [Guru99 Bank Home Page]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title does not matched expected [uru99 Bank Home Page] but found [Guru99 Bank Home Page]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.TC01_Verify_login_Functionality.verify_TitleAndHeader(TC01_Verify_login_Functionality.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_TitleAndHeader -->
        <test-method signature="login_with_Invalid_Credentials()[pri:2, instance:testcases.TC01_Verify_login_Functionality@44821a96]" started-at="2021-11-29T21:20:54 IST" name="login_with_Invalid_Credentials" finished-at="2021-11-29T21:20:55 IST" duration-ms="611" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_with_Invalid_Credentials -->
        <test-method signature="login_with_Valid_Credentials()[pri:3, instance:testcases.TC01_Verify_login_Functionality@44821a96]" started-at="2021-11-29T21:20:55 IST" name="login_with_Valid_Credentials" finished-at="2021-11-29T21:20:57 IST" duration-ms="2844" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_with_Valid_Credentials -->
        <test-method is-config="true" signature="quit()[pri:0, instance:testcases.TC01_Verify_login_Functionality@44821a96]" started-at="2021-11-29T21:20:59 IST" name="quit" finished-at="2021-11-29T21:20:59 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- testcases.TC01_Verify_login_Functionality -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
